### ISSUE TITLE
package.json file not exist

### ISSUE THREAD

**Issue by kemalturk-venhancer** [Saifullah-dev/react-file-manager#86]

**Comment by Saifullah-dev** [comment]
@kemalturk-venhancer The `package.json` file is not located in the root directory because the project is split into two parts: **frontend** and **backend**, each with its own `package.json`. You can find these files inside their respective directories:

- [frontend/package.json](https://github.com/Saifullah-dev/react-file-manager/blob/main/frontend/package.json)
- [backend/package.json](https://github.com/Saifullah-dev/react-file-manager/blob/main/backend/package.json)

This separation allows for more modular management of dependencies specific to each part of the application.
